import AetherHero from '@/components/main/hero/AetherHero';
import Navbar from '@/components/main/navbar/Navbar';

export default function Home() {
  return (
    <main>
      <Navbar />
      <AetherHero
        title="Viral Thumbnails, Generated by AI."
        subtitle="Just describe your video — Nailart AI crafts scroll-stopping YouTube thumbnails in seconds."
        ctaLabel="Get Started Free"
        ctaHref="#generate"
        secondaryCtaLabel="See Examples"
        secondaryCtaHref="#examples"
        align="center"
      />
    </main>
  );
}
